### ISSUE TITLE
Need some startup tutorial

### ISSUE THREAD

**Issue by RYG81** [SmallPlanetUnity/PlanetUnity2#1]
Hi Can we have some tutorial to start with it?
a simple read me like material will be OK too.

Can we use WPF layout inside Unity using this?

**Comment by danm3d** [comment]
Yeah, a quick start guide would be really helpful

**Comment by sagron** [comment]
After playing with it a bit I got it working on Unity 5.2 by doing the following:
<table>
<tr><td>
1. Load LeanTween from the asset store (free)
</td></tr>
<tr><td>
2. Fix LeanTween access permissions errors in PUTable.cs by replacing
<code>tableCell.puGameObject.canvasGroup.alpha = LeanTween.easeInCubic (0, 1, distance / cellTransform.rect.height);</code>
<br>with<br>
<code>LeanTween.alpha(tableCell.puGameObject.canvasGroup.gameObject, 1, distance / cellTransform.rect.height).setEase(LeanTweenType.easeInCubic);</code>
</td></tr>
<tr><td>
3. Fix LeanTween access permissions errors in PUTable.cs by replacing
<code>tableCell.puGameObject.canvasGroup.alpha = LeanTween.easeInCubic (0, 1, (bottomOfCell+cellTransform.rect.height) / cellTransform.rect.height);</code>
<br>with<br> 
<code>LeanTween.alpha(tableCell.puGameObject.canvasGroup.gameObject, 1, (bottomOfCell + cellTransform.rect.height) / cellTransform.rect.height).setEase(LeanTweenType.easeInCubic);</code>
</td></tr>
<tr><td>
4. Changing pre-processor tags (using unity 5.2 so didn't need the OnPopulateMesh or OnFillVBO methods
</td></tr>
<tr><td>
5. Make a Resources folder with the following xml file in it (rename from txt to xml)
<a href="https://github.com/SmallPlanetUnity/PlanetUnity2/files/43302/PlanetUnityTestXML.txt">[PlanetUnityTestXML.txt]</a>
</td></tr>
<tr><td>
6. Create an empty gameobject
</td></tr>
<tr><td>
7. On your empty gameobject add component Scripts -> Planet Unity Game Object
</td></tr>
<tr><td>
8. In the Xml Path on the script set to the name of the xml file (PlanetUnityTestXML) with no extension
</td></tr>
<tr><td>
9. Either have editor preview enabled or hit play
</td></tr>
</table>

I think that's everything :).

**Comment by RYG81** [comment]
thanks Sagron

**Comment by RYG81** [comment]
@Sagron can you share your project?

**Comment by RYG81** [comment]
OK, not needed now
it is working hello world.

**Comment by RYG81** [comment]
Playing with it now, can some one help me find documentation for the markup?
There is only one video showing some exciting stuff, but a readup for all the features would be more helpful.

**Comment by sagron** [comment]
Only thing I've really found for documentation so far is looking at the xsd file - gives you the tags, attributes (and attribute types) and  enumeration values.

**Comment by KittyMac** [comment]
Initial documentation and example project added.  Better late than never ;)

https://github.com/SmallPlanetUnity/PlanetUnity2/blob/master/Documentation/TableOfContents.md
