### ISSUE TITLE
Elements are not centered

### ISSUE THREAD

**Issue by MihailTrajkovski** [SmallPlanetUnity/PlanetUnity2#2]
I've tried the simple example(the introductory one with color red) and the element is off centered and it's position it's not 0,0,0,0 like in the tutorial but some other values(for example for a resolution of 800x1280 i get the values 400,640,-400,-640).

Does this package works with unity 2017? I really like the package hope it will work on this version,

**Comment by KittyMac** [comment]
Unity 2017 should be supported.  PlanetUnity exposes the underlying Unity UI stuff, and Unity is pretty notorious for making breaking changes there even across minor revisions.  There were some fixes for unity 2017.2.0f3 that were sitting on a branch, i moved them over to master (specifically there were some issues around Canvas no longer getting set to be stretch,stretch correctly).
